import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ['latin'] });
const MasterLayout = dynamic(()=> import("@/components/layout/master"))

export const metadata: Metadata = {
  title: "WeatherEase - App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
              <body className={inter.className}>
                  <MasterLayout>
                      {children}
                  </MasterLayout>
              </body>
        </html>
  );
}
